### ISSUE TITLE
你好能提供一下pcap吗

### ISSUE THREAD

**Issue by WX-T** [shyoshyo/DataCon-9102-DNS#1]
你好能提供一下pcap数据文件吗

**Comment by shyoshyo** [comment]
不好意思，这个我目前无法提供。比赛主办方禁止参赛选手直接将比赛数据提供给第三方，因此抱歉还得麻烦您直接与主办方沟通。

附：数据使用声明：
DataCon大数据安全分析比赛的比赛数据资源（包括但不限于，任何计算机程序、代码（包括源代码和目标代码）、算法、公式、过程、观念、图表、照片、制图、设计、产品、样品、发明创造（包括发明、实用新型和外观设计，无论是否获得专利）、技术秘密、硬件配置、系统结构、版权、商标、产品研发计划、预测、策划、规范、实际或潜在商业活动的信息、与第三方的协议、客户与供应商信息、财务信息、市场营销计划等技术、商务上的信息，以下简称“比赛数据”）所有权归主办方360企业安全集团及清华大学所有。报名审核通过的参赛选手（下称“报名者”）可通过比赛官网butian.net/datacon下载比赛数据参赛。无论报名者最终是否参加比赛，默认报名者知晓且同意：

1、大赛组委会提供的比赛数据仅供比赛使用，任何通过大赛获取到比赛数据的单位和个人，不得将数据用于比赛之外的其他用途，否则应由侵权人直接向相关权利人承担责任。

2、报名者不得以任何方式（包括但不限于口头、书面、影印、复制、交付、摄影、传阅、电子传送、纸质发表或其他方式）将部分或全部比赛数据披露给其他第三方，或使其他第三方获得比赛数据。

3、大赛组委会不对任何对比赛数据使用、披露、转让、传输、编辑、整理、分析、修改大赛数据等任何操作或行为所产生的一切法律后果承担任何责任，应由侵权人直接向相关权利人承担责任。

4、除主办方书面免除外，报名者对比赛数据的保密义务应为永久。

参赛者报名审核通过后，在2019年3月29日开赛后方可下载比赛数据。下载比赛数据之后未实际参赛的，报名者应当立即删除经大赛数据库下载的、保存在计算机和/或其他设备中的所有比赛数据。比赛结束后，主办方会将部分数据面向学术研究开放，比赛数据使用的最终解释权归比赛主办方所有。
